### ISSUE TITLE
getsoc.sh: Zeile 84: ((: 1700387316 >=  : Syntax Fehler

### ISSUE THREAD

**Issue by steviean** [hhoefling/citigo#3]
Nachdem ich das Citigo_SOC-Modul mal wieder auf den aktuellen Stand bringen wollte, läuft es leider nicht mehr. 
Bei Aufruf von 

`pi@raspberrypi:/var/www/html/lp1 $ ./soc_citigo/getsoc.sh`

kommt die Meldung:

`./soc_citigo/getsoc.sh: Zeile 84: ((: 1700387316 >=  : Syntax Fehler: Operator erwartet. (Fehlerverursachendes Zeichen ist \">=  \").
`

und in der Zeile 84 steht: `if (( $diff >= $minold )) ; then`

Was mache ich falsch?

**Comment by hhoefling** [comment]
In der getconf.conf ist ein Paramter dazugekommen der in der Doku-Readme nich nicht erwähnt war.
Also bitte diese beiden Zeilen zur getsoc.conf hinzufügen

````
# Mindestabstand der abfragen
minold: 30

````

**Comment by hhoefling** [comment]
Anaonsten muste ich vor einigen Tagen eine Anüassung am skodaconnect machen die hier noch nicht eingescheckt ist.

**Comment by hhoefling** [comment]
Stimmt nicht.,
Die User-Agent anpassung ist doch schin drin ( in skodaconnect)

**Comment by steviean** [comment]
Oha, da ist wirklich Einiges anders. Läuft es denn bei Dir noch? 

`pi@raspberrypi:/var/www/html/lp1 $ ./soc_citigo/getsoc.sh
callskoda.py for LP1 debug:1
Init Skoda Connect library, version 1.3.8
dump:False
Initiating new session to Skoda Connect with fxxx.kxxx@xxx.de as username
Attempting to login to the Skoda Connect service
2023-11-19 16:34:13.551500
WARNING:skodaconnect.connection:Token for technical could not be verified, verification returned public_key() missing 1 required positional argument: 'backend'.
Login success!
2023-11-19 16:34:14.731679
Fetching vehicles associated with account.
WARNING:skodaconnect.connection:Token for connect could not be verified, verification returned public_key() missing 1 required positional argument: 'backend'.
Traceback (most recent call last):
  File "callskoda.py", line 378, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "callskoda.py", line 224, in main
    typ = type(eval(func))
  File "<string>", line 1, in <module>
  File "/var/www/html/lp1/soc_citigo/skodaconnect/vehicle.py", line 2293, in aux_heater_for_departure
    if self.departure1.get('heaterSource', 'electric') == 'automatic':
AttributeError: 'NoneType' object has no attribute 'get'
`

Jetzt will er die Heizung und was weiß ich noch alles abfragen...

**Comment by hhoefling** [comment]
Naja zur 1.3.8'er Version kann ich nichts sagen,.
Mit meinem Citiygo klappt die hier abgelegte 1.1.14 weiterhin.

**Comment by steviean** [comment]
Stimmt, mit der (glücklicher Weise von Dir abgelegten) Version funktioniert es tatsächlich wieder. Wird der SOC jetzt sogar per MQTT an die OpenWB gesendet? Ich hatte nämlich temporär das "Manuelle Soc-Modul" konfiguriert, aber scheinbar hat die OpenWB den aktuellen nun auch so bekommen. 
Auf jedem Fall VIELEN DANK!

**Comment by hhoefling** [comment]
Ja, MQTT wird versorgt wenn aktiviert.
Wenn du Manuell-SOC altiv hast kann der SOC Wert aber etwas "Hoppeln" weil  er aus zwei Quelle versorgt wird.

**Comment by hhoefling** [comment]
Ok. Ich mal hier zu
